// Regenerates docs/DATABASE_SCHEMA.sql straight from the live database (introspecting
// information_schema/pg_catalog) instead of maintaining it by hand alongside 39+
// migrations — which is exactly how it drifted out of sync in the first place (12 tables
// and a dozen+ columns missing, confirmed by the code audit). No pg_dump binary needed —
// same reasoning as run-sql.js: uses the `pg` package already in package.json, so it works
// the same on Windows/macOS/Linux with nothing extra to install.
//
// Usage (from the backend/ folder):
//   node scripts/dump-schema.js
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

// Map information_schema's data_type back to the short SQL spelling this file already
// uses elsewhere (VARCHAR(n) not "character varying", DECIMAL(p,s) not "numeric", etc.)
function formatType(col) {
  switch (col.data_type) {
    case 'character varying':
      return col.character_maximum_length ? `VARCHAR(${col.character_maximum_length})` : 'VARCHAR';
    case 'numeric':
      return col.numeric_precision != null ? `DECIMAL(${col.numeric_precision}, ${col.numeric_scale ?? 0})` : 'DECIMAL';
    case 'timestamp without time zone':
      return 'TIMESTAMP';
    case 'time without time zone':
      return 'TIME';
    case 'integer':
      return 'INT';
    case 'boolean':
      return 'BOOLEAN';
    case 'text':
      return 'TEXT';
    case 'jsonb':
      return 'JSONB';
    case 'date':
      return 'DATE';
    case 'uuid':
      return 'UUID';
    case 'ARRAY':
      return `${(col.udt_name || '').replace(/^_/, '').toUpperCase()}[]`;
    default:
      return (col.udt_name || col.data_type).toUpperCase();
  }
}

async function run() {
  if (!process.env.DATABASE_URL) {
    console.error('DATABASE_URL is not set — check that .env sits next to package.json and you ran this from the backend/ folder.');
    process.exitCode = 1;
    return;
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  try {
    const tablesResult = await pool.query(
      `SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename`
    );
    const tableNames = tablesResult.rows.map((r) => r.tablename);
    const sequencesResult = await pool.query(
      `SELECT sequencename, start_value, increment_by
       FROM pg_sequences WHERE schemaname = 'public' ORDER BY sequencename`
    );

    const lines = [
      '-- AUTO-GENERATED by scripts/dump-schema.js from the live database — do not hand-edit.',
      `-- Regenerated: ${new Date().toISOString().slice(0, 10)}`,
      '-- Run again after any migration: node scripts/dump-schema.js',
      '',
    ];

    for (const sequence of sequencesResult.rows) {
      lines.push(
        `CREATE SEQUENCE ${sequence.sequencename} START WITH ${sequence.start_value} INCREMENT BY ${sequence.increment_by};`,
        ''
      );
    }

    for (const table of tableNames) {
      const columnsResult = await pool.query(
        `SELECT column_name, data_type, udt_name, character_maximum_length, numeric_precision, numeric_scale,
                is_nullable, column_default
         FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = $1
         ORDER BY ordinal_position`,
        [table]
      );

      const pkResult = await pool.query(
        `SELECT a.attname FROM pg_index i
         JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
         WHERE i.indrelid = $1::regclass AND i.indisprimary`,
        [table]
      );
      const pkCols = pkResult.rows.map((r) => r.attname);

      const fkResult = await pool.query(
        `SELECT con.conname AS constraint_name, source_col.attname AS column_name,
                target.relname AS foreign_table, target_col.attname AS foreign_column,
                CASE con.confdeltype
                  WHEN 'c' THEN 'CASCADE' WHEN 'r' THEN 'RESTRICT'
                  WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT'
                  ELSE 'NO ACTION'
                END AS delete_rule,
                source_key.ordinality AS ordinal_position
         FROM pg_constraint con
         JOIN pg_class source ON source.oid = con.conrelid
         JOIN pg_namespace source_ns ON source_ns.oid = source.relnamespace
         JOIN pg_class target ON target.oid = con.confrelid
         CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS source_key(attnum, ordinality)
         JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS target_key(attnum, ordinality)
           ON target_key.ordinality = source_key.ordinality
         JOIN pg_attribute source_col ON source_col.attrelid = source.oid AND source_col.attnum = source_key.attnum
         JOIN pg_attribute target_col ON target_col.attrelid = target.oid AND target_col.attnum = target_key.attnum
         WHERE source_ns.nspname = 'public' AND source.relname = $1 AND con.contype = 'f'
         ORDER BY con.conname, source_key.ordinality`,
        [table]
      );
      const foreignKeys = [];
      for (const row of fkResult.rows) {
        let fk = foreignKeys.find((candidate) => candidate.name === row.constraint_name);
        if (!fk) {
          fk = {
            name: row.constraint_name,
            columns: [],
            foreignTable: row.foreign_table,
            foreignColumns: [],
            deleteRule: row.delete_rule,
          };
          foreignKeys.push(fk);
        }
        fk.columns.push(row.column_name);
        fk.foreignColumns.push(row.foreign_column);
      }
      const fkByColumn = new Map(
        foreignKeys.filter((fk) => fk.columns.length === 1).map((fk) => [fk.columns[0], fk])
      );
      const compositeForeignKeys = foreignKeys.filter((fk) => fk.columns.length > 1);

      const uniqueResult = await pool.query(
        // ::text cast matters: column_name is information_schema's "sql_identifier" domain
        // type, and array_agg over a domain produces an array OID node-postgres doesn't
        // have a built-in parser for — it comes back as a raw "{a,b}" string instead of a
        // JS array without this cast.
        `SELECT tc.constraint_name, array_agg(kcu.column_name::text ORDER BY kcu.ordinal_position) AS cols
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         WHERE tc.table_schema = 'public' AND tc.table_name = $1 AND tc.constraint_type = 'UNIQUE'
         GROUP BY tc.constraint_name`,
        [table]
      );
      const singleColUnique = new Set();
      const compositeUnique = [];
      for (const row of uniqueResult.rows) {
        const cols = Array.isArray(row.cols) ? row.cols : row.cols.replace(/^\{|\}$/g, '').split(',');
        if (cols.length === 1) singleColUnique.add(cols[0]);
        else compositeUnique.push(cols);
      }

      lines.push(`CREATE TABLE ${table} (`);
      const colLines = columnsResult.rows.map((col) => {
        const parts = [`  ${col.column_name} ${formatType(col)}`];
        if (pkCols.length === 1 && pkCols[0] === col.column_name) parts.push('PRIMARY KEY');
        if (col.is_nullable === 'NO' && !(pkCols.length === 1 && pkCols[0] === col.column_name)) parts.push('NOT NULL');
        if (col.column_default != null) parts.push(`DEFAULT ${col.column_default}`);
        const fk = fkByColumn.get(col.column_name);
        if (fk) {
          let ref = `REFERENCES ${fk.foreignTable}(${fk.foreignColumns[0]})`;
          if (fk.deleteRule && fk.deleteRule !== 'NO ACTION') ref += ` ON DELETE ${fk.deleteRule}`;
          parts.push(ref);
        }
        if (singleColUnique.has(col.column_name)) parts.push('UNIQUE');
        return parts.join(' ');
      });
      if (pkCols.length > 1) colLines.push(`  PRIMARY KEY (${pkCols.join(', ')})`);
      for (const fk of compositeForeignKeys) {
        let definition = `  CONSTRAINT ${fk.name} FOREIGN KEY (${fk.columns.join(', ')}) REFERENCES ${fk.foreignTable}(${fk.foreignColumns.join(', ')})`;
        if (fk.deleteRule && fk.deleteRule !== 'NO ACTION') definition += ` ON DELETE ${fk.deleteRule}`;
        colLines.push(definition);
      }
      for (const cols of compositeUnique) colLines.push(`  UNIQUE (${cols.join(', ')})`);
      lines.push(colLines.join(',\n'));
      lines.push(');');
      lines.push('');
    }

    const outPath = path.resolve(__dirname, '..', 'docs', 'DATABASE_SCHEMA.sql');
    fs.writeFileSync(outPath, lines.join('\n'));
    console.log(`✅ Wrote ${tableNames.length} tables to ${outPath}`);
  } catch (err) {
    console.error('❌ Failed.');
    console.error('  message:', err && err.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
}

run();
