// Regenerates docs/DATABASE_SCHEMA.sql straight from the live database (introspecting
// information_schema/pg_catalog) instead of maintaining it by hand alongside 39+
// migrations — which is exactly how it drifted out of sync in the first place (12 tables
// and a dozen+ columns missing, confirmed by the code audit). No pg_dump binary needed —
// same reasoning as run-sql.js: uses the `pg` package already in package.json, so it works
// the same on Windows/macOS/Linux with nothing extra to install.
//
// Usage (from the backend/ folder):
//   node scripts/dump-schema.js
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

// Map information_schema's data_type back to the short SQL spelling this file already
// uses elsewhere (VARCHAR(n) not "character varying", DECIMAL(p,s) not "numeric", etc.)
function formatType(col) {
  switch (col.data_type) {
    case 'character varying':
      return col.character_maximum_length ? `VARCHAR(${col.character_maximum_length})` : 'VARCHAR';
    case 'numeric':
      return col.numeric_precision != null ? `DECIMAL(${col.numeric_precision}, ${col.numeric_scale ?? 0})` : 'DECIMAL';
    case 'timestamp without time zone':
      return 'TIMESTAMP';
    case 'time without time zone':
      return 'TIME';
    case 'integer':
      return 'INT';
    case 'boolean':
      return 'BOOLEAN';
    case 'text':
      return 'TEXT';
    case 'jsonb':
      return 'JSONB';
    case 'date':
      return 'DATE';
    case 'uuid':
      return 'UUID';
    case 'ARRAY':
      return `${(col.udt_name || '').replace(/^_/, '').toUpperCase()}[]`;
    default:
      return (col.udt_name || col.data_type).toUpperCase();
  }
}

async function run() {
  if (!process.env.DATABASE_URL) {
    console.error('DATABASE_URL is not set — check that .env sits next to package.json and you ran this from the backend/ folder.');
    process.exitCode = 1;
    return;
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  try {
    const tablesResult = await pool.query(
      `SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename`
    );
    const tableNames = tablesResult.rows.map((r) => r.tablename);

    const lines = [
      '-- AUTO-GENERATED by scripts/dump-schema.js from the live database — do not hand-edit.',
      `-- Regenerated: ${new Date().toISOString().slice(0, 10)}`,
      '-- Run again after any migration: node scripts/dump-schema.js',
      '',
    ];

    for (const table of tableNames) {
      const columnsResult = await pool.query(
        `SELECT column_name, data_type, udt_name, character_maximum_length, numeric_precision, numeric_scale,
                is_nullable, column_default
         FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = $1
         ORDER BY ordinal_position`,
        [table]
      );

      const pkResult = await pool.query(
        `SELECT a.attname FROM pg_index i
         JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
         WHERE i.indrelid = $1::regclass AND i.indisprimary`,
        [table]
      );
      const pkCols = pkResult.rows.map((r) => r.attname);

      const fkResult = await pool.query(
        `SELECT kcu.column_name, ccu.table_name AS foreign_table, ccu.column_name AS foreign_column, rc.delete_rule
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
         JOIN information_schema.referential_constraints rc ON rc.constraint_name = tc.constraint_name AND rc.constraint_schema = tc.table_schema
         WHERE tc.table_schema = 'public' AND tc.table_name = $1 AND tc.constraint_type = 'FOREIGN KEY'`,
        [table]
      );
      const fkByColumn = new Map(fkResult.rows.map((r) => [r.column_name, r]));

      const uniqueResult = await pool.query(
        `SELECT tc.constraint_name, array_agg(kcu.column_name ORDER BY kcu.ordinal_position) AS cols
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         WHERE tc.table_schema = 'public' AND tc.table_name = $1 AND tc.constraint_type = 'UNIQUE'
         GROUP BY tc.constraint_name`,
        [table]
      );
      const singleColUnique = new Set();
      const compositeUnique = [];
      for (const row of uniqueResult.rows) {
        if (row.cols.length === 1) singleColUnique.add(row.cols[0]);
        else compositeUnique.push(row.cols);
      }

      lines.push(`CREATE TABLE ${table} (`);
      const colLines = columnsResult.rows.map((col) => {
        const parts = [`  ${col.column_name} ${formatType(col)}`];
        if (pkCols.length === 1 && pkCols[0] === col.column_name) parts.push('PRIMARY KEY');
        if (col.is_nullable === 'NO' && !(pkCols.length === 1 && pkCols[0] === col.column_name)) parts.push('NOT NULL');
        if (col.column_default != null) parts.push(`DEFAULT ${col.column_default}`);
        const fk = fkByColumn.get(col.column_name);
        if (fk) {
          let ref = `REFERENCES ${fk.foreign_table}(${fk.foreign_column})`;
          if (fk.delete_rule && fk.delete_rule !== 'NO ACTION') ref += ` ON DELETE ${fk.delete_rule}`;
          parts.push(ref);
        }
        if (singleColUnique.has(col.column_name)) parts.push('UNIQUE');
        return parts.join(' ');
      });
      if (pkCols.length > 1) colLines.push(`  PRIMARY KEY (${pkCols.join(', ')})`);
      for (const cols of compositeUnique) colLines.push(`  UNIQUE (${cols.join(', ')})`);
      lines.push(colLines.join(',\n'));
      lines.push(');');
      lines.push('');
    }

    const outPath = path.resolve(__dirname, '..', 'docs', 'DATABASE_SCHEMA.sql');
    fs.writeFileSync(outPath, lines.join('\n'));
    console.log(`✅ Wrote ${tableNames.length} tables to ${outPath}`);
  } catch (err) {
    console.error('❌ Failed.');
    console.error('  message:', err && err.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
}

run();
