-- AUTO-GENERATED by scripts/dump-schema.js from the live database — do not hand-edit.
-- Regenerated: 2026-08-22
-- Run again after any migration: node scripts/dump-schema.js

CREATE TABLE api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  key_hash VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  last_used_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'active'::character varying
);

CREATE TABLE attendance_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  clock_in TIMESTAMP,
  clock_out TIMESTAMP,
  late_minutes INT DEFAULT 0,
  deduction_amount DECIMAL(10, 3) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'present'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (employee_id, date)
);

CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id),
  action VARCHAR(50),
  entity_type VARCHAR(50),
  entity_id UUID,
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  user_agent VARCHAR(500),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE cash_denominations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  denomination DECIMAL(10, 3),
  count INT,
  total DECIMAL(10, 3),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  plan VARCHAR(20) DEFAULT 'trial'::character varying,
  subscription_status VARCHAR(20) DEFAULT 'trial'::character varying,
  trial_start_date TIMESTAMP DEFAULT now(),
  trial_end_date TIMESTAMP DEFAULT (now() + '14 days'::interval),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  fixed_cost_items JSONB DEFAULT '[]'::jsonb,
  estimated_orders_mode VARCHAR(10) DEFAULT 'auto'::character varying,
  estimated_orders_manual INT,
  default_jahez_commission_pct DECIMAL(5, 2) DEFAULT 23,
  default_vthru_commission_pct DECIMAL(5, 2) DEFAULT 23,
  official_shift_start_time TIME DEFAULT '08:00:00'::time without time zone,
  grace_period_minutes INT DEFAULT 15,
  working_days_per_month INT DEFAULT 26,
  standard_shift_minutes INT DEFAULT 480,
  industry VARCHAR(100),
  employee_count_range VARCHAR(20),
  country VARCHAR(2) DEFAULT 'KW'::character varying,
  street VARCHAR(255),
  building_number VARCHAR(50),
  district VARCHAR(100),
  city VARCHAR(100),
  postal_code VARCHAR(20),
  commercial_registration_number VARCHAR(50),
  tax_registration_number VARCHAR(50),
  fiscal_year_end_month INT DEFAULT 12,
  contact_email VARCHAR(255),
  contact_phone VARCHAR(30),
  logo_base64 TEXT,
  stamp_base64 TEXT,
  inventory_enabled BOOLEAN DEFAULT true,
  delivery_notifications_enabled BOOLEAN DEFAULT true,
  two_factor_required BOOLEAN DEFAULT false,
  expense_categories JSONB DEFAULT '["إيجار", "صيانة", "مشتريات مخزون", "تسويق", "فواتير"]'::jsonb,
  default_sales_notes TEXT
);

CREATE TABLE company_files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(30) NOT NULL DEFAULT 'other'::character varying,
  file_base64 TEXT,
  file_name VARCHAR(255),
  issue_date DATE,
  expiry_date DATE,
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE conflict_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id),
  table_name VARCHAR(50),
  record_id UUID,
  server_version JSONB,
  client_version JSONB,
  resolution VARCHAR(50),
  resolved_by UUID,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE custom_fields (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  field_type VARCHAR(20) NOT NULL DEFAULT 'text'::character varying,
  applies_to VARCHAR(30) NOT NULL DEFAULT 'official_documents'::character varying,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE customer_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
  amount DECIMAL(12, 3) NOT NULL,
  receipt_date DATE NOT NULL DEFAULT CURRENT_DATE,
  method VARCHAR(30) NOT NULL DEFAULT 'cash'::character varying,
  notes TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(255),
  points INT NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  code VARCHAR(20),
  country VARCHAR(2) DEFAULT 'KW'::character varying,
  city VARCHAR(120),
  street VARCHAR(255),
  building_number VARCHAR(50),
  district VARCHAR(120),
  postal_code VARCHAR(20),
  relation VARCHAR(20) NOT NULL DEFAULT 'customer'::character varying,
  contact_person VARCHAR(255),
  payment_terms VARCHAR(50),
  commercial_registration_number VARCHAR(50)
);

CREATE TABLE document_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL DEFAULT 'الافتراضي'::character varying,
  is_default BOOLEAN DEFAULT true,
  logo_base64 TEXT,
  primary_color VARCHAR(9) DEFAULT '#f59e0b'::character varying,
  footer_text TEXT,
  show_stamp BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20),
  job_role VARCHAR(100),
  salary_monthly DECIMAL(10, 3),
  start_date DATE,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  photo_base64 TEXT,
  civil_id VARCHAR(30),
  birth_date DATE,
  weight_kg DECIMAL(5, 2),
  prior_experience TEXT,
  certificates JSONB DEFAULT '[]'::jsonb,
  wage_type VARCHAR(10) DEFAULT 'monthly'::character varying,
  hourly_rate DECIMAL(10, 3),
  nationality VARCHAR(100),
  civil_id_expiry DATE,
  residency_number VARCHAR(50),
  residency_expiry DATE,
  passport_number VARCHAR(50),
  passport_expiry DATE,
  bank_iban VARCHAR(50),
  emergency_contact_name VARCHAR(150),
  emergency_contact_phone VARCHAR(30),
  location_id UUID REFERENCES locations(id),
  allowances JSONB DEFAULT '[]'::jsonb,
  shift_start_time TIME,
  late_grace_minutes INT
);

CREATE TABLE expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category VARCHAR(100),
  amount DECIMAL(10, 3),
  description VARCHAR(500),
  receipt_image TEXT,
  created_at TIMESTAMP DEFAULT now(),
  created_by UUID REFERENCES users(id),
  location_id UUID REFERENCES locations(id),
  expense_date DATE
);

CREATE TABLE invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  subscription_id UUID REFERENCES subscriptions(id),
  amount DECIMAL(10, 3),
  status VARCHAR(20) DEFAULT 'pending'::character varying,
  issue_date TIMESTAMP,
  due_date TIMESTAMP,
  payment_date TIMESTAMP,
  telr_transaction_id VARCHAR(255),
  pdf_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE leave_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  start_time TIME,
  end_time TIME,
  reason TEXT,
  attachment_base64 TEXT,
  status VARCHAR(20) DEFAULT 'pending'::character varying,
  reviewed_by UUID REFERENCES users(id),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  manager_note TEXT
);

CREATE TABLE locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(500),
  area VARCHAR(100),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  type VARCHAR(20) DEFAULT 'kiosk'::character varying
);

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT,
  link VARCHAR(255),
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE official_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  reference_number VARCHAR(50) NOT NULL,
  doc_type VARCHAR(30) NOT NULL,
  title VARCHAR(255) NOT NULL,
  addressed_to_employee_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  addressed_to_name VARCHAR(255),
  document_date DATE NOT NULL,
  body TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, reference_number)
);

CREATE TABLE payroll (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id),
  month_year VARCHAR(7),
  base_salary DECIMAL(10, 3),
  attendance_bonus DECIMAL(10, 3) DEFAULT 0,
  other_deductions DECIMAL(10, 3) DEFAULT 0,
  total_paid DECIMAL(10, 3),
  status VARCHAR(20) DEFAULT 'pending'::character varying,
  paid_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  wage_type VARCHAR(10) DEFAULT 'monthly'::character varying,
  hourly_rate DECIMAL(10, 3),
  hours_worked DECIMAL(10, 2),
  attendance_deduction DECIMAL(10, 3) DEFAULT 0,
  UNIQUE (employee_id, month_year)
);

CREATE TABLE payroll_adjustments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  payroll_id UUID NOT NULL REFERENCES payroll(id) ON DELETE CASCADE,
  type VARCHAR(10) NOT NULL,
  label VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 3) NOT NULL,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE product_ingredients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  usage_qty DECIMAL(10, 3),
  usage_unit VARCHAR(20),
  is_packaging BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (product_id, raw_material_id)
);

CREATE TABLE product_size_ingredients (
  product_size_id UUID NOT NULL REFERENCES product_sizes(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  usage_qty DECIMAL(10, 3),
  usage_unit VARCHAR(20),
  is_packaging BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (product_size_id, raw_material_id)
);

CREATE TABLE product_sizes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  name_en VARCHAR(100),
  sell_price DECIMAL(10, 3),
  sort_order INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100),
  sell_price DECIMAL(10, 3),
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  name_en VARCHAR(255),
  has_sizes BOOLEAN DEFAULT false
);

CREATE TABLE purchase_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  qty DECIMAL(10, 3) NOT NULL,
  unit_price DECIMAL(10, 3) NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  supplier_id UUID REFERENCES suppliers(id),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  order_date DATE,
  expected_date DATE,
  received_date DATE,
  location_id UUID REFERENCES locations(id),
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE raw_material_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id) ON DELETE CASCADE,
  purchase_date DATE NOT NULL,
  expiry_date DATE,
  qty_purchased DECIMAL(10, 3) NOT NULL,
  qty_remaining DECIMAL(10, 3) NOT NULL,
  purchase_price DECIMAL(10, 3) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  location_id UUID NOT NULL REFERENCES locations(id),
  unit VARCHAR(10) NOT NULL DEFAULT 'g'::character varying
);

CREATE TABLE raw_materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50),
  package_qty DECIMAL(10, 3),
  package_unit VARCHAR(20),
  purchase_price DECIMAL(10, 3),
  supplier_name VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  name_en VARCHAR(255),
  min_stock_qty DECIMAL(10, 3),
  supplier_id UUID REFERENCES suppliers(id)
);

CREATE TABLE recurring_invoice_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id UUID NOT NULL REFERENCES recurring_invoice_templates(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE recurring_invoice_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  frequency VARCHAR(10) NOT NULL DEFAULT 'monthly'::character varying,
  next_run_date DATE NOT NULL DEFAULT CURRENT_DATE,
  active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  product_id UUID NOT NULL REFERENCES products(id),
  qty DECIMAL(10, 3) NOT NULL,
  unit_price DECIMAL(10, 3),
  total_price DECIMAL(10, 3),
  payment_method VARCHAR(20),
  app_commission_pct DECIMAL(5, 2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT now(),
  created_by UUID REFERENCES users(id),
  version INT DEFAULT 1,
  product_size_id UUID REFERENCES product_sizes(id),
  cost_of_goods DECIMAL(10, 3)
);

CREATE TABLE sales_credit_note_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credit_note_id UUID NOT NULL REFERENCES sales_credit_notes(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_credit_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  source_invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE sales_invoice_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id UUID NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  source_quote_id UUID REFERENCES sales_quotes(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  type VARCHAR(10) NOT NULL DEFAULT 'invoice'::character varying
);

CREATE TABLE sales_quote_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL REFERENCES sales_quotes(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE shift_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id),
  assigned_qty DECIMAL(10, 3),
  remaining_qty DECIMAL(10, 3),
  created_at TIMESTAMP DEFAULT now(),
  product_size_id UUID REFERENCES product_sizes(id),
  actual_remaining_qty DECIMAL(10, 3)
);

CREATE TABLE shift_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  location_id UUID REFERENCES locations(id),
  date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE shifts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES employees(id),
  location_id UUID REFERENCES locations(id),
  date DATE NOT NULL,
  opened_at TIMESTAMP,
  closed_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'open'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  closing_notes TEXT
);

CREATE TABLE stock_adjustments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  location_id UUID NOT NULL REFERENCES locations(id),
  qty_delta DECIMAL(10, 3) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  new_batch_id UUID REFERENCES raw_material_batches(id),
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE stock_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  from_location_id UUID NOT NULL REFERENCES locations(id),
  to_location_id UUID NOT NULL REFERENCES locations(id),
  qty DECIMAL(10, 3) NOT NULL,
  new_batch_id UUID REFERENCES raw_material_batches(id),
  transferred_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  plan VARCHAR(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  monthly_price DECIMAL(10, 3),
  auto_renew BOOLEAN DEFAULT true,
  next_billing_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  phone VARCHAR(20),
  email VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES users(id),
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'open'::character varying,
  priority VARCHAR(20) DEFAULT 'medium'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE sync_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id),
  device_id VARCHAR(255),
  last_sync_timestamp TIMESTAMP,
  last_synced_version INT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE ticket_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id),
  message TEXT NOT NULL,
  is_admin_reply BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE user_permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_key VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE (user_id, permission_key)
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  full_name VARCHAR(255),
  role VARCHAR(20) NOT NULL DEFAULT 'employee'::character varying,
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  job_title VARCHAR(100),
  phone VARCHAR(30),
  google_id VARCHAR(255) UNIQUE,
  auth_provider VARCHAR(20) NOT NULL DEFAULT 'password'::character varying,
  email_verified_at TIMESTAMP,
  password_reset_token_hash VARCHAR(64),
  password_reset_expires_at TIMESTAMP
);

CREATE TABLE version_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name VARCHAR(50) NOT NULL,
  record_id UUID NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  version INT NOT NULL,
  old_values JSONB,
  new_values JSONB,
  changed_by UUID REFERENCES users(id),
  changed_at TIMESTAMP DEFAULT now(),
  reason VARCHAR(255)
);

CREATE TABLE waste_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  product_id UUID NOT NULL REFERENCES products(id),
  qty DECIMAL(10, 3),
  image_base64 TEXT,
  created_at TIMESTAMP DEFAULT now(),
  cost_of_goods DECIMAL(10, 3)
);
