-- AUTO-GENERATED by scripts/dump-schema.js from the live database — do not hand-edit.
-- Regenerated: 2026-09-26
-- Run again after any migration: node scripts/dump-schema.js

CREATE SEQUENCE macrocore_invoice_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  key_hash VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  last_used_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'active'::character varying
);

CREATE TABLE appraisal_form_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  form_id UUID NOT NULL REFERENCES appraisal_forms(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  question_text_en TEXT,
  question_type VARCHAR(20) NOT NULL DEFAULT 'rating'::character varying,
  max_score DECIMAL(6, 2) DEFAULT 5,
  weight DECIMAL(5, 2) DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE appraisal_forms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE approval_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  module_type VARCHAR(50) NOT NULL,
  reference_id UUID NOT NULL,
  requester_id UUID NOT NULL REFERENCES employees(id),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
  current_step INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  request_number VARCHAR(30),
  sla_deadline_at TIMESTAMPTZ,
  sla_reminder_sent_at TIMESTAMPTZ,
  sla_breached_at TIMESTAMPTZ
);

CREATE TABLE approval_steps_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  approval_request_id UUID NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
  step_number INT NOT NULL,
  approver_id UUID REFERENCES employees(id),
  action VARCHAR(20) NOT NULL,
  comments TEXT,
  action_at TIMESTAMP DEFAULT now(),
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE approval_workflow_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  module_type VARCHAR(50) NOT NULL,
  step_number INT NOT NULL,
  approver_type VARCHAR(30) NOT NULL,
  approver_value VARCHAR(120),
  step_label VARCHAR(120) NOT NULL,
  step_label_en VARCHAR(120),
  UNIQUE (module_type, step_number)
);

CREATE TABLE attendance_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  clock_in TIMESTAMP,
  clock_out TIMESTAMP,
  late_minutes INT DEFAULT 0,
  deduction_amount DECIMAL(10, 3) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'present'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (employee_id, date)
);

CREATE TABLE audit_log_field_changes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_log_id UUID NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  field_name VARCHAR(100) NOT NULL,
  old_value TEXT,
  new_value TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id),
  action VARCHAR(50),
  entity_type VARCHAR(50),
  entity_id UUID,
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  user_agent VARCHAR(500),
  created_at TIMESTAMP DEFAULT now(),
  prev_hash VARCHAR(64),
  hash VARCHAR(64)
);

CREATE TABLE audit_logs_archive (
  id UUID PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id),
  action VARCHAR(50),
  entity_type VARCHAR(50),
  entity_id UUID,
  old_values JSONB,
  new_values JSONB,
  ip_address VARCHAR(50),
  user_agent VARCHAR(500),
  created_at TIMESTAMP,
  archived_at TIMESTAMP NOT NULL DEFAULT now(),
  prev_hash VARCHAR(64),
  hash VARCHAR(64)
);

CREATE TABLE cash_denominations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  denomination DECIMAL(10, 3),
  count INT,
  total DECIMAL(10, 3),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE closed_periods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  closed_by UUID REFERENCES employees(id) ON DELETE SET NULL,
  period_year INT NOT NULL,
  period_month INT NOT NULL,
  closed_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, period_year, period_month)
);

CREATE TABLE companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  plan VARCHAR(20) DEFAULT 'trial'::character varying,
  subscription_status VARCHAR(20) DEFAULT 'trial'::character varying,
  trial_start_date TIMESTAMP DEFAULT now(),
  trial_end_date TIMESTAMP DEFAULT (now() + '14 days'::interval),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  fixed_cost_items JSONB DEFAULT '[]'::jsonb,
  estimated_orders_mode VARCHAR(10) DEFAULT 'auto'::character varying,
  estimated_orders_manual INT,
  default_jahez_commission_pct DECIMAL(5, 2) DEFAULT 23,
  default_vthru_commission_pct DECIMAL(5, 2) DEFAULT 23,
  official_shift_start_time TIME DEFAULT '08:00:00'::time without time zone,
  grace_period_minutes INT DEFAULT 15,
  working_days_per_month INT DEFAULT 26,
  standard_shift_minutes INT DEFAULT 480,
  industry VARCHAR(100),
  employee_count_range VARCHAR(20),
  country VARCHAR(2) DEFAULT 'KW'::character varying,
  street VARCHAR(255),
  building_number VARCHAR(50),
  district VARCHAR(100),
  city VARCHAR(100),
  postal_code VARCHAR(20),
  commercial_registration_number VARCHAR(50),
  tax_registration_number VARCHAR(50),
  fiscal_year_end_month INT DEFAULT 12,
  contact_email VARCHAR(255),
  contact_phone VARCHAR(30),
  logo_base64 TEXT,
  stamp_base64 TEXT,
  inventory_enabled BOOLEAN DEFAULT true,
  delivery_notifications_enabled BOOLEAN DEFAULT true,
  two_factor_required BOOLEAN DEFAULT false,
  expense_categories JSONB DEFAULT '["إيجار", "صيانة", "مشتريات مخزون", "تسويق", "فواتير"]'::jsonb,
  default_sales_notes TEXT,
  timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Kuwait'::character varying,
  whatsapp_alert_number VARCHAR(20),
  whatsapp_alerts_enabled BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE company_files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(30) NOT NULL DEFAULT 'other'::character varying,
  file_base64 TEXT,
  file_name VARCHAR(255),
  issue_date DATE,
  expiry_date DATE,
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE conflict_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id),
  table_name VARCHAR(50),
  record_id UUID,
  server_version JSONB,
  client_version JSONB,
  resolution VARCHAR(50),
  resolved_by UUID,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE cost_centers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  manager_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, code)
);

CREATE TABLE custom_fields (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  field_type VARCHAR(20) NOT NULL DEFAULT 'text'::character varying,
  applies_to VARCHAR(30) NOT NULL DEFAULT 'official_documents'::character varying,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE customer_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
  amount DECIMAL(12, 3) NOT NULL,
  receipt_date DATE NOT NULL DEFAULT CURRENT_DATE,
  method VARCHAR(30) NOT NULL DEFAULT 'cash'::character varying,
  notes TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(255),
  points INT NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  code VARCHAR(20),
  country VARCHAR(2) DEFAULT 'KW'::character varying,
  city VARCHAR(120),
  street VARCHAR(255),
  building_number VARCHAR(50),
  district VARCHAR(120),
  postal_code VARCHAR(20),
  relation VARCHAR(20) NOT NULL DEFAULT 'customer'::character varying,
  contact_person VARCHAR(255),
  payment_terms VARCHAR(50),
  commercial_registration_number VARCHAR(50)
);

CREATE TABLE departments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  parent_department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  manager_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  cost_center_code VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  code VARCHAR(10)
);

CREATE TABLE document_sequences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  prefix VARCHAR(50) NOT NULL,
  current_value INT NOT NULL DEFAULT 0,
  UNIQUE (company_id, prefix)
);

CREATE TABLE document_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL DEFAULT 'الافتراضي'::character varying,
  is_default BOOLEAN DEFAULT true,
  logo_base64 TEXT,
  primary_color VARCHAR(9) DEFAULT '#f59e0b'::character varying,
  footer_text TEXT,
  show_stamp BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE email_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  svix_id VARCHAR(255) NOT NULL UNIQUE,
  email_job_id UUID REFERENCES email_jobs(id) ON DELETE SET NULL,
  event_type VARCHAR(50) NOT NULL,
  resend_message_id VARCHAR(255),
  payload JSONB NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT now(),
  applied_at TIMESTAMP,
  reconcile_attempts INT NOT NULL DEFAULT 0,
  next_reconcile_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE email_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  category VARCHAR(50) NOT NULL,
  dedup_key VARCHAR(300) NOT NULL UNIQUE,
  recipient_email VARCHAR(255) NOT NULL,
  lang VARCHAR(2) NOT NULL DEFAULT 'ar'::character varying,
  subject TEXT NOT NULL,
  html TEXT NOT NULL,
  reply_to VARCHAR(255),
  related_entity_type VARCHAR(50),
  related_entity_id UUID,
  status VARCHAR(20) NOT NULL DEFAULT 'queued'::character varying,
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 5,
  next_attempt_at TIMESTAMP NOT NULL DEFAULT now(),
  claimed_at TIMESTAMP,
  claimed_by VARCHAR(100),
  resend_message_id VARCHAR(255),
  last_error TEXT,
  last_attempted_at TIMESTAMP,
  sent_at TIMESTAMP,
  delivered_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE email_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  category VARCHAR(50) NOT NULL,
  recipient_email VARCHAR(255) NOT NULL,
  subject TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  resend_message_id VARCHAR(255),
  related_entity_type VARCHAR(50),
  related_entity_id UUID,
  error TEXT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE employee_invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  full_name VARCHAR(255),
  invited_by UUID REFERENCES users(id) ON DELETE SET NULL,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  accepted_at TIMESTAMP,
  accepted_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  revoked_at TIMESTAMP,
  revoked_by UUID REFERENCES users(id) ON DELETE SET NULL,
  preferred_language VARCHAR(2) NOT NULL DEFAULT 'ar'::character varying,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (company_id, email)
);

CREATE TABLE employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20),
  job_role VARCHAR(100),
  salary_monthly DECIMAL(10, 3),
  start_date DATE,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  photo_base64 TEXT,
  civil_id VARCHAR(30),
  birth_date DATE,
  weight_kg DECIMAL(5, 2),
  prior_experience TEXT,
  certificates JSONB DEFAULT '[]'::jsonb,
  wage_type VARCHAR(10) DEFAULT 'monthly'::character varying,
  hourly_rate DECIMAL(10, 3),
  nationality VARCHAR(100),
  civil_id_expiry DATE,
  residency_number VARCHAR(50),
  residency_expiry DATE,
  passport_number VARCHAR(50),
  passport_expiry DATE,
  bank_iban VARCHAR(50),
  emergency_contact_name VARCHAR(150),
  emergency_contact_phone VARCHAR(30),
  location_id UUID REFERENCES locations(id),
  allowances JSONB DEFAULT '[]'::jsonb,
  shift_start_time TIME,
  late_grace_minutes INT,
  department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  job_role_id UUID REFERENCES job_roles(id) ON DELETE SET NULL,
  manager_id UUID REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category VARCHAR(100),
  amount DECIMAL(10, 3),
  description VARCHAR(500),
  receipt_image TEXT,
  created_at TIMESTAMP DEFAULT now(),
  created_by UUID REFERENCES users(id),
  location_id UUID REFERENCES locations(id),
  expense_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'approved'::character varying
);

CREATE TABLE feedback_answers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  feedback_request_id UUID NOT NULL REFERENCES feedback_requests(id) ON DELETE CASCADE,
  question_id UUID NOT NULL REFERENCES appraisal_form_questions(id),
  score DECIMAL(6, 2),
  comment TEXT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE feedback_cycles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  form_id UUID REFERENCES appraisal_forms(id),
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE feedback_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  cycle_id UUID NOT NULL REFERENCES feedback_cycles(id) ON DELETE CASCADE,
  subject_employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  reviewer_employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  reviewer_type VARCHAR(20) NOT NULL DEFAULT 'peer'::character varying,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
  overall_score DECIMAL(6, 2),
  submitted_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  subscription_id UUID NOT NULL,
  amount DECIMAL(10, 3) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'issued'::character varying,
  issue_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  due_date TIMESTAMPTZ NOT NULL,
  payment_date TIMESTAMPTZ,
  telr_transaction_id VARCHAR(255),
  pdf_url VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  plan VARCHAR(20) NOT NULL,
  billing_interval VARCHAR(10) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  invoice_number VARCHAR(20) NOT NULL DEFAULT ('MC-SUB-'::text || lpad((nextval('macrocore_invoice_number_seq'::regclass))::text, 6, '0'::text)) UNIQUE,
  CONSTRAINT invoices_subscription_company_fk FOREIGN KEY (subscription_id, company_id) REFERENCES subscriptions(id, company_id) ON DELETE RESTRICT,
  UNIQUE (id, company_id, subscription_id),
  UNIQUE (subscription_id, period_start, period_end)
);

CREATE TABLE job_role_permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  job_role_id UUID NOT NULL REFERENCES job_roles(id) ON DELETE CASCADE,
  permission_key VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE (job_role_id, permission_key)
);

CREATE TABLE job_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  department_id UUID NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  responsibilities TEXT
);

CREATE TABLE leave_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  start_time TIME,
  end_time TIME,
  reason TEXT,
  attachment_base64 TEXT,
  status VARCHAR(20) DEFAULT 'pending'::character varying,
  reviewed_by UUID REFERENCES users(id),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  manager_note TEXT,
  category VARCHAR(20) NOT NULL DEFAULT 'leave'::character varying,
  permission_reason VARCHAR(30),
  notice_received_by VARCHAR(20)
);

CREATE TABLE locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(500),
  area VARCHAR(100),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  type VARCHAR(20) DEFAULT 'kiosk'::character varying,
  manager_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  cost_center_code VARCHAR(50),
  contact_phone VARCHAR(50),
  gps_coordinates VARCHAR(255),
  municipality_license VARCHAR(100),
  license_expiry_date DATE,
  lease_expiry_date DATE
);

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT,
  link VARCHAR(255),
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  approval_request_id UUID REFERENCES approval_requests(id) ON DELETE SET NULL
);

CREATE TABLE official_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  reference_number VARCHAR(50) NOT NULL,
  doc_type VARCHAR(30) NOT NULL,
  title VARCHAR(255) NOT NULL,
  addressed_to_employee_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  addressed_to_name VARCHAR(255),
  document_date DATE NOT NULL,
  body TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, reference_number)
);

CREATE TABLE okr_key_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  objective_id UUID NOT NULL REFERENCES okr_objectives(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255),
  metric_type VARCHAR(20) NOT NULL DEFAULT 'number'::character varying,
  unit VARCHAR(30),
  target_value DECIMAL(14, 3),
  current_value DECIMAL(14, 3) DEFAULT 0,
  weight DECIMAL(5, 2) DEFAULT 1,
  status VARCHAR(20) NOT NULL DEFAULT 'on_track'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  start_value DECIMAL(14, 3) DEFAULT 0
);

CREATE TABLE okr_objectives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255),
  description TEXT,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  progress_pct DECIMAL(5, 2) DEFAULT 0,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE payment_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id UUID NOT NULL,
  company_id UUID NOT NULL,
  subscription_id UUID NOT NULL,
  amount DECIMAL(10, 3) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  plan VARCHAR(20) NOT NULL,
  billing_interval VARCHAR(10) NOT NULL,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'initiated'::character varying,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  failed_at TIMESTAMPTZ,
  succeeded_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  CONSTRAINT payment_attempts_invoice_company_subscription_fk FOREIGN KEY (invoice_id, company_id, subscription_id) REFERENCES invoices(id, company_id, subscription_id) ON DELETE RESTRICT
);

CREATE TABLE payment_checkout_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_attempt_id UUID NOT NULL REFERENCES payment_attempts(id) ON DELETE RESTRICT UNIQUE,
  provider VARCHAR(20) NOT NULL DEFAULT 'simulated'::character varying,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'::character varying,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

CREATE TABLE payroll (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id),
  month_year VARCHAR(7),
  base_salary DECIMAL(10, 3),
  attendance_bonus DECIMAL(10, 3) DEFAULT 0,
  other_deductions DECIMAL(10, 3) DEFAULT 0,
  total_paid DECIMAL(10, 3),
  status VARCHAR(20) DEFAULT 'pending'::character varying,
  paid_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  wage_type VARCHAR(10) DEFAULT 'monthly'::character varying,
  hourly_rate DECIMAL(10, 3),
  hours_worked DECIMAL(10, 2),
  attendance_deduction DECIMAL(10, 3) DEFAULT 0,
  UNIQUE (employee_id, month_year)
);

CREATE TABLE payroll_adjustments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  payroll_id UUID NOT NULL REFERENCES payroll(id) ON DELETE CASCADE,
  type VARCHAR(10) NOT NULL,
  label VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 3) NOT NULL,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE pending_permission_grants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_key VARCHAR(50) NOT NULL,
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
  requested_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (company_id, user_id, permission_key)
);

CREATE TABLE performance_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  cycle_id UUID REFERENCES feedback_cycles(id),
  okr_score DECIMAL(6, 2),
  feedback_score DECIMAL(6, 2),
  final_score DECIMAL(6, 2),
  bonus_amount DECIMAL(10, 3) DEFAULT 0,
  payroll_adjustment_id UUID REFERENCES payroll_adjustments(id),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (employee_id, cycle_id)
);

CREATE TABLE policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255),
  content TEXT NOT NULL,
  content_en TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  module_linked VARCHAR(30),
  version INT NOT NULL DEFAULT 1,
  created_by UUID REFERENCES users(id),
  reviewed_by UUID REFERENCES users(id),
  approved_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE policy_acknowledgments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  acknowledged_at TIMESTAMP NOT NULL DEFAULT now(),
  ip_address VARCHAR(50),
  device_info TEXT,
  UNIQUE (company_id, policy_id, employee_id)
);

CREATE TABLE policy_permission_gates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
  permission_key VARCHAR(50) NOT NULL,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (company_id, permission_key)
);

CREATE TABLE product_ingredients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  usage_qty DECIMAL(10, 3),
  usage_unit VARCHAR(20),
  is_packaging BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (product_id, raw_material_id)
);

CREATE TABLE product_size_ingredients (
  product_size_id UUID NOT NULL REFERENCES product_sizes(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  usage_qty DECIMAL(10, 3),
  usage_unit VARCHAR(20),
  is_packaging BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (product_size_id, raw_material_id)
);

CREATE TABLE product_sizes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  name_en VARCHAR(100),
  sell_price DECIMAL(10, 3),
  sort_order INT DEFAULT 0,
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100),
  sell_price DECIMAL(10, 3),
  status VARCHAR(20) DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  name_en VARCHAR(255),
  has_sizes BOOLEAN DEFAULT false
);

CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  cost_center_id UUID REFERENCES cost_centers(id) ON DELETE SET NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  manager_id UUID REFERENCES employees(id) ON DELETE SET NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  budget DECIMAL(14, 3) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, code)
);

CREATE TABLE purchase_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  qty DECIMAL(10, 3) NOT NULL,
  unit_price DECIMAL(10, 3) NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  supplier_id UUID REFERENCES suppliers(id),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  order_date DATE,
  expected_date DATE,
  received_date DATE,
  location_id UUID REFERENCES locations(id),
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE raw_material_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id) ON DELETE CASCADE,
  purchase_date DATE NOT NULL,
  expiry_date DATE,
  qty_purchased DECIMAL(10, 3) NOT NULL,
  qty_remaining DECIMAL(10, 3) NOT NULL,
  purchase_price DECIMAL(10, 3) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  location_id UUID NOT NULL REFERENCES locations(id),
  unit VARCHAR(10) NOT NULL DEFAULT 'g'::character varying
);

CREATE TABLE raw_materials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50),
  package_qty DECIMAL(10, 3),
  package_unit VARCHAR(20),
  purchase_price DECIMAL(10, 3),
  supplier_name VARCHAR(255),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  name_en VARCHAR(255),
  min_stock_qty DECIMAL(10, 3),
  supplier_id UUID REFERENCES suppliers(id)
);

CREATE TABLE recurring_invoice_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id UUID NOT NULL REFERENCES recurring_invoice_templates(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE recurring_invoice_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  frequency VARCHAR(10) NOT NULL DEFAULT 'monthly'::character varying,
  next_run_date DATE NOT NULL DEFAULT CURRENT_DATE,
  active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE request_type_approval_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_type_id UUID NOT NULL REFERENCES service_request_types(id) ON DELETE CASCADE,
  step_number INT NOT NULL,
  approver_type VARCHAR(30) NOT NULL,
  approver_job_role_id UUID REFERENCES job_roles(id) ON DELETE SET NULL,
  step_label VARCHAR(120) NOT NULL,
  step_label_en VARCHAR(120),
  UNIQUE (request_type_id, step_number)
);

CREATE TABLE role_policy_requirements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, policy_id, role)
);

CREATE TABLE sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  product_id UUID NOT NULL REFERENCES products(id),
  qty DECIMAL(10, 3) NOT NULL,
  unit_price DECIMAL(10, 3),
  total_price DECIMAL(10, 3),
  payment_method VARCHAR(20),
  app_commission_pct DECIMAL(5, 2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT now(),
  created_by UUID REFERENCES users(id),
  version INT DEFAULT 1,
  product_size_id UUID REFERENCES product_sizes(id),
  cost_of_goods DECIMAL(10, 3)
);

CREATE TABLE sales_credit_note_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  credit_note_id UUID NOT NULL REFERENCES sales_credit_notes(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_credit_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  source_invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE sales_invoice_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id UUID NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  source_quote_id UUID REFERENCES sales_quotes(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  type VARCHAR(10) NOT NULL DEFAULT 'invoice'::character varying
);

CREATE TABLE sales_quote_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL REFERENCES sales_quotes(id) ON DELETE CASCADE,
  description VARCHAR(500) NOT NULL,
  qty DECIMAL(12, 3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12, 3) NOT NULL DEFAULT 0,
  line_total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  discount_pct DECIMAL(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sales_quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  number VARCHAR(30) NOT NULL,
  customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'draft'::character varying,
  notes TEXT,
  subtotal DECIMAL(12, 3) NOT NULL DEFAULT 0,
  total DECIMAL(12, 3) NOT NULL DEFAULT 0,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE service_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  name_en VARCHAR(120),
  description VARCHAR(500),
  description_en VARCHAR(500),
  icon VARCHAR(60),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE service_custom_fields (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  request_type_id UUID REFERENCES service_request_types(id) ON DELETE CASCADE,
  field_key VARCHAR(60) NOT NULL,
  field_label VARCHAR(120) NOT NULL,
  field_label_en VARCHAR(120),
  field_type VARCHAR(20) NOT NULL DEFAULT 'text'::character varying,
  is_required BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE service_request_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category_id UUID REFERENCES service_categories(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  name_en VARCHAR(120),
  description VARCHAR(500),
  description_en VARCHAR(500),
  is_hr_sensitive BOOLEAN NOT NULL DEFAULT false,
  source_ticket_category_id UUID,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  requires_approval BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE shift_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id),
  assigned_qty DECIMAL(10, 3),
  remaining_qty DECIMAL(10, 3),
  created_at TIMESTAMP DEFAULT now(),
  product_size_id UUID REFERENCES product_sizes(id),
  actual_remaining_qty DECIMAL(10, 3)
);

CREATE TABLE shift_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  location_id UUID REFERENCES locations(id),
  date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE shifts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES employees(id),
  location_id UUID REFERENCES locations(id),
  date DATE NOT NULL,
  opened_at TIMESTAMP,
  closed_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'open'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  closing_notes TEXT
);

CREATE TABLE sla_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  priority VARCHAR(20) NOT NULL,
  response_minutes INT NOT NULL DEFAULT 240,
  resolution_minutes INT NOT NULL DEFAULT 1440,
  escalate_after_minutes INT,
  escalate_to_role VARCHAR(20) DEFAULT 'admin'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE (company_id, priority)
);

CREATE TABLE stock_adjustments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  location_id UUID NOT NULL REFERENCES locations(id),
  qty_delta DECIMAL(10, 3) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  new_batch_id UUID REFERENCES raw_material_batches(id),
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE stock_transfers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  raw_material_id UUID NOT NULL REFERENCES raw_materials(id),
  from_location_id UUID NOT NULL REFERENCES locations(id),
  to_location_id UUID NOT NULL REFERENCES locations(id),
  qty DECIMAL(10, 3) NOT NULL,
  new_batch_id UUID REFERENCES raw_material_batches(id),
  transferred_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE subscription_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  subscription_id UUID NOT NULL UNIQUE,
  invoice_id UUID NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'open'::character varying,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  voided_at TIMESTAMPTZ,
  replaces_subscription_id UUID,
  CONSTRAINT subscription_purchases_invoice_fk FOREIGN KEY (invoice_id, company_id, subscription_id) REFERENCES invoices(id, company_id, subscription_id) ON DELETE RESTRICT,
  CONSTRAINT subscription_purchases_replaces_fk FOREIGN KEY (replaces_subscription_id, company_id) REFERENCES subscriptions(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT subscription_purchases_subscription_fk FOREIGN KEY (subscription_id, company_id) REFERENCES subscriptions(id, company_id) ON DELETE RESTRICT
);

CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  plan VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  monthly_price DECIMAL(10, 3),
  auto_renew BOOLEAN DEFAULT true,
  next_billing_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  currency VARCHAR(3) NOT NULL,
  billing_interval VARCHAR(10) NOT NULL,
  current_period_start TIMESTAMPTZ NOT NULL,
  current_period_end TIMESTAMPTZ NOT NULL,
  period_amount DECIMAL(10, 3) NOT NULL,
  UNIQUE (id, company_id)
);

CREATE TABLE suppliers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  phone VARCHAR(20),
  email VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES users(id),
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'open'::character varying,
  priority VARCHAR(20) DEFAULT 'medium'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  category VARCHAR(30) NOT NULL DEFAULT 'general'::character varying,
  assigned_to UUID REFERENCES users(id),
  first_response_at TIMESTAMP,
  resolved_at TIMESTAMP,
  sla_response_due_at TIMESTAMPTZ,
  sla_resolution_due_at TIMESTAMPTZ,
  sla_response_breached BOOLEAN DEFAULT false,
  sla_resolution_breached BOOLEAN DEFAULT false,
  escalation_level INT DEFAULT 0,
  escalated_to UUID REFERENCES users(id),
  escalated_at TIMESTAMP,
  category_id UUID REFERENCES ticket_categories(id) ON DELETE SET NULL,
  request_type_id UUID REFERENCES service_request_types(id) ON DELETE SET NULL,
  dynamic_data JSONB DEFAULT '{}'::jsonb,
  ticket_number VARCHAR(50),
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  sla_response_escalated_at TIMESTAMPTZ,
  sla_resolution_escalated_at TIMESTAMPTZ,
  sla_last_swept_at TIMESTAMPTZ
);

CREATE TABLE sync_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id),
  device_id VARCHAR(255),
  last_sync_timestamp TIMESTAMP,
  last_synced_version INT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE ticket_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  name_en VARCHAR(100),
  is_hr_sensitive BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE ticket_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id),
  message TEXT NOT NULL,
  is_admin_reply BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  is_internal_note BOOLEAN NOT NULL DEFAULT false,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE user_permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_key VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  UNIQUE (user_id, permission_key)
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  full_name VARCHAR(255),
  role VARCHAR(20) NOT NULL DEFAULT 'employee'::character varying,
  status VARCHAR(20) NOT NULL DEFAULT 'active'::character varying,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  job_title VARCHAR(100),
  phone VARCHAR(30),
  google_id VARCHAR(255) UNIQUE,
  auth_provider VARCHAR(20) NOT NULL DEFAULT 'password'::character varying,
  email_verified_at TIMESTAMP,
  password_reset_token_hash VARCHAR(64),
  password_reset_expires_at TIMESTAMP,
  employee_id UUID REFERENCES employees(id),
  preferred_language VARCHAR(2) NOT NULL DEFAULT 'ar'::character varying
);

CREATE TABLE version_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name VARCHAR(50) NOT NULL,
  record_id UUID NOT NULL,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  version INT NOT NULL,
  old_values JSONB,
  new_values JSONB,
  changed_by UUID REFERENCES users(id),
  changed_at TIMESTAMP DEFAULT now(),
  reason VARCHAR(255)
);

CREATE TABLE waste_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  shift_id UUID NOT NULL REFERENCES shifts(id),
  product_id UUID NOT NULL REFERENCES products(id),
  qty DECIMAL(10, 3),
  image_base64 TEXT,
  created_at TIMESTAMP DEFAULT now(),
  cost_of_goods DECIMAL(10, 3)
);
