-- MIGRATION_083_subscription_invoice_foundation.sql
-- Stage B3 — Macrocore Subscription Invoice Foundation (see
-- claude/chat4a-b3-subscription-invoice-foundation-proposal-2026-09-15.md,
-- Revision 2 + the Implementation section appended after it).
--
-- Additive, plus two corrective changes carried from Revision 2's independent
-- review: (1) invoices.company_id's foreign key changes from ON DELETE CASCADE
-- to ON DELETE RESTRICT — a Macrocore-issued invoice must never be silently
-- destroyed as a side effect of a tenant deleting their own company (see
-- company.controller.ts::deleteMe(), refactored alongside this migration to
-- check for existing invoices before deleting); (2) a dedicated global
-- invoice-numbering sequence replaces the tenant-scoped document_sequences
-- table, which is the wrong shape for a document Macrocore itself issues
-- across every customer company (see PREFLIGHT_B3_invoices_schema_check.js
-- and the B3 proposal §2 for the full reasoning).
--
-- A production preflight was reported (not independently re-run by this
-- session — no database credentials are held here) before Revision 2 was
-- finalized, and confirmed: 0 rows in `invoices`, the live
-- invoices_company_id_fkey constraint named exactly as referenced below, and
-- no target column/constraint/sequence from this migration already existing.
-- Because the table is genuinely empty, every new or tightened column below
-- is NOT NULL outright — there is no legacy data to backfill or accommodate
-- with a nullable-compatibility variant (the same reasoning MIGRATION_082
-- used for `subscriptions`). PREFLIGHT_B3_invoices_schema_check.js
-- (this stage's own new script, mirroring PREFLIGHT_B2's structure) MUST be
-- run against the real target database and its output reviewed BEFORE this
-- file is ever run there — it has not been run against production by this
-- session either.
--
-- No production write has happened as part of preparing this file. Claude
-- executed this exact migration successfully against a disposable PostgreSQL
-- database and separately ran the B3 concurrency smoke checks. Production
-- still requires a fresh preflight review before this file is run there.
--
-- Run from backend/: node scripts/run-sql.js docs/MIGRATION_083_subscription_invoice_foundation.sql

BEGIN;

-- Global, cross-tenant invoice-numbering sequence. Deliberately NOT
-- document_sequences (UNIQUE (company_id, prefix)) — that table scopes a
-- counter to the company issuing its OWN document to itself (a ticket
-- number, an approval number). Macrocore's subscription invoices run the
-- opposite direction (issued BY Macrocore TO its tenant companies) and must
-- be unique across ALL companies; a tenant-scoped counter would let two
-- different customers each be issued e.g. "SUB-2609-0001" in the same month
-- — the wrong scope entirely, not merely inconvenient.
--
-- nextval() on a plain sequence is NOT transactional: a rolled-back
-- transaction still permanently consumes the number it drew, so numbers can
-- have GAPS after a failed or rolled-back invoice insert (e.g. MC-SUB-000004
-- followed by MC-SUB-000006, with 000005 never issued to anyone). This is
-- expected in this design. Allocated values are never reused; invoice-number
-- order follows sequence allocation and is not a promise of gap-free or
-- transaction-commit ordering.
CREATE SEQUENCE macrocore_invoice_number_seq START WITH 1;

ALTER TABLE invoices
  -- Every B3-created invoice is, by design, always tied to a specific
  -- subscription — an invoice row with a NULL subscription_id would
  -- contradict the "immutable snapshot of a subscription" model this whole
  -- stage is built on.
  ALTER COLUMN subscription_id SET NOT NULL,

  -- TIMESTAMPTZ for every timestamp this stage introduces or actively
  -- normalizes — see claude/sla-timezone-incident-2026-09-09.md for why a
  -- plain TIMESTAMP column is not acceptable here. issue_date and due_date
  -- are always generated by the application from the SAME captured instant
  -- (never two separate now()/new Date() calls), so they are exactly equal
  -- for every invoice this stage creates — see createSubscriptionInvoice in
  -- admin.controller.ts. Table is empty, so no USING clause / data
  -- reinterpretation is needed for the TYPE changes below.
  ALTER COLUMN issue_date TYPE TIMESTAMPTZ,
  ALTER COLUMN issue_date SET NOT NULL,
  ALTER COLUMN issue_date SET DEFAULT now(),
  ALTER COLUMN due_date TYPE TIMESTAMPTZ,
  ALTER COLUMN due_date SET NOT NULL,
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN created_at SET NOT NULL,

  -- The pre-existing `amount` column remains the invoice's exact charge —
  -- it is not reconstructed from `subscriptions.monthly_price`, and no
  -- parallel `period_amount` column is introduced on `invoices` (there was
  -- no legacy-data reason to hedge with a second column once the preflight
  -- confirmed the table was empty).
  ALTER COLUMN amount SET NOT NULL,

  -- One real status for this stage: 'issued' — the row was created; payment
  -- is unverified; it does NOT mean paid, failed, overdue, refunded, or
  -- voided. The CHECK constraint below permits only this value for now; a
  -- later stage widens it once a real paid/void/etc. transition exists, the
  -- same way B2's own subscriptions.status set only grew as real
  -- transitions were built.
  ALTER COLUMN status SET DEFAULT 'issued',
  ALTER COLUMN status SET NOT NULL,

  -- Immutable commercial snapshot columns, copied verbatim from the active
  -- subscription at issue time and never re-derived afterward, so a later
  -- change to that subscription (a future plan change, a currency change,
  -- etc.) can never retroactively alter an already-issued invoice.
  ADD COLUMN plan VARCHAR(20) NOT NULL,
  ADD COLUMN billing_interval VARCHAR(10) NOT NULL,
  ADD COLUMN currency VARCHAR(3) NOT NULL,
  ADD COLUMN period_start TIMESTAMPTZ NOT NULL,
  ADD COLUMN period_end TIMESTAMPTZ NOT NULL,

  -- Explicitly approved and preferred over an application-side nextval()
  -- call: the controller simply omits invoice_number from its INSERT column
  -- list and reads the generated value back from RETURNING *. Functionally
  -- identical to an explicit nextval() call — the same "let Postgres do the
  -- one thing it's already good at" reasoning the existing
  -- `id UUID DEFAULT gen_random_uuid()` column already uses.
  ADD COLUMN invoice_number VARCHAR(20) NOT NULL
    DEFAULT ('MC-SUB-' || LPAD(nextval('macrocore_invoice_number_seq')::text, 6, '0')),

  ADD CONSTRAINT invoices_amount_positive CHECK (amount > 0),
  ADD CONSTRAINT invoices_currency_supported CHECK (currency IN ('USD','KWD')),
  ADD CONSTRAINT invoices_billing_interval_valid CHECK (billing_interval IN ('monthly','annual')),
  ADD CONSTRAINT invoices_period_end_after_start CHECK (period_end > period_start),
  ADD CONSTRAINT invoices_due_on_or_after_issue CHECK (due_date >= issue_date),
  ADD CONSTRAINT invoices_status_valid CHECK (status IN ('issued')),

  -- At most one invoice per subscription period — the actual, concurrency-
  -- safe duplicate guard (never an application-level precheck alone, which
  -- would itself race). admin.controller.ts's createSubscriptionInvoice
  -- checks err.constraint === 'invoices_one_invoice_per_period' specifically
  -- before treating a unique violation as "already invoiced this period" —
  -- any other unique violation (e.g. an astronomically unlikely
  -- invoice_number collision on the sequence) is left to propagate as a
  -- real error, never silently swallowed as a normal duplicate.
  ADD CONSTRAINT invoices_one_invoice_per_period UNIQUE (subscription_id, period_start, period_end),

  -- Global uniqueness (locked decision F) — not scoped to company_id.
  ADD CONSTRAINT invoices_number_unique UNIQUE (invoice_number);

-- Corrective change (Revision 2 §3): a Macrocore-issued subscription invoice
-- must never disappear as a side effect of a tenant deleting their own
-- company through company.controller.ts::deleteMe(). RESTRICT is the final,
-- concurrency-safe protection — deleteMe() also gains its own precheck (for
-- a clear 409 instead of a raw FK-violation error), but the precheck alone
-- has a race window that only the database constraint actually closes; see
-- the paired regression tests proving both lock orders. The exact
-- constraint name below was confirmed live by the preflight check before
-- this file was finalized.
ALTER TABLE invoices DROP CONSTRAINT invoices_company_id_fkey;
ALTER TABLE invoices ADD CONSTRAINT invoices_company_id_fkey
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT;

COMMIT;

-- Left deliberately untouched, per the approved design:
--   * telr_transaction_id, pdf_url — nullable, unused, no provider semantics
--     attached in this stage.
--   * payment_date — stays plain TIMESTAMP, nullable, unused by B3. Flagging
--     explicitly for whoever designs the future payment stage: convert it to
--     TIMESTAMPTZ *before* any code ever writes to it — do not repeat the
--     SLA timezone mistake by writing real values into a column that is
--     still the wrong type. This is a note for that future stage, not a B3
--     action item.
--   * invoices_subscription_id_fkey — stays as-is (no ON DELETE specified,
--     i.e. NO ACTION); no code path in this codebase deletes subscriptions,
--     so this needs no correction right now.
--   * document_sequences, sales_invoices, sales_invoice_items — untouched;
--     both are separate mechanisms from Macrocore's own invoices table.
